title: Hello, world! I'm Bruno Brito
description: > # this means to ignore newlines until "baseurl:"
  My research is focused on data-driven motion planning techniques for autonomous navigation among
  humans and other robots. More specifically, I have been developing autonomous navigation algorithms
  combining optimization-based and learning-based techniques (e.g., Model Predictive Control and Deep
  Reinforcement Learning).
permalink: ':title/'
domain: bbrito.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: "https://bbrito.github.io"  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: "/"     # place folder name if the site is served in a subfolder
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Bruno Brito # add your name
author-img: bruno_brito.jpg # add your photo
about-author: I am a PhD Candidate at TU Delft in the Cognitive Robotics (CoR) department. Always hungry to keep learning. # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: bbrito # add your Github handle
social-linkedin: https://www.linkedin.com/in/bruno-brito-1b815338/
social-email: bruno.debrito@tudelft.nl

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
